services:
  shome-web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/data
  shome-rabbitmq:
    image: rabbitmq:management
#    command: "/bin/bash -c \"rabbitmq-plugins enable rabbitmq_mqtt\ rabbitmq-plugins enable rabbitmq_management\ rabbitmqctl add_user test test\ rabbitmqctl set_user_tags test administrator\ rabbitmqctl set_permissions -p / test "".*"" "".*"" "".*""\ rabbitmq-server\""
    ports:
      - "1883:1883"
      - "15672:15672"
    volumes:
      - "./rabbitmq:/etc/rabbitmq"